spring.application.name=gestion-sinistre-rag
server.port=8080

ollama.base-url=http://localhost:11434
ollama.chat-model=deepseek-r1:1.5b
ollama.embedding-model=nomic-embed-text

# Milvus
milvus.host=localhost
milvus.port=19530
milvus.collection-name=sinistre
milvus.dimension=768

# Logging
logging.level.com.sinistre=DEBUG
logging.level.dev.langchain4j=INFO

# Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB